spring:
  application:
    name: readforce
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://124.5.240.195:5432/readforce
    username: readforce_admin
    password: 1234
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        hbm2ddl:
          auto: validate
  data:
    redis:
      host: localhost
      port: 6379
  mail:
    host: smtp.gmail.com
    port: 587
    username: readforce2002@gmail.com
    password: tudyftdrnttukroj
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  jwt:
    secret: Dekndke3!@$ndkWkf@42Sk*dn!$DNkDj3a@ane#ganD
    expiration-time: 3600000
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope: 
              - email
          naver:
            client-id: ${NAVER_CLIENT_ID}
            client-secret: ${NAVER_CLIENT_SECRET}
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope:
              - email
            client-name: Naver
          kakao:
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope:
              - account_email
            client-name: Kakao
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

file:
  image:
    profile:
      upload-dir: ./upload/image/profile/
      max-size: 5242880
      allowed-mime-types: image/jpeg,image/png,image/gif
custom:
  fronted:
    password-reset-link-url: http://localhost:3000/resetpassword
    social-login-success:
      exist-member-url: http://localhost:3000/auth/callback
      new-member-url: http://localhost:3000/social-sign-up
newsapi:
  key: 52047c836f2d4b659280136c95e8132c
gemini:
  key: AIzaSyCM4bos91g7zvIEbXvmwjsjYRN3ma2tMD4
